name: CD Pipeline

on:
  push:
    branches:
      - main  # Only deploy from main branch after passing CI

jobs:
  deploy:
    runs-on: ubuntu-latest

    needs: test  # Optional if splitting from CI — skip if workflows are separate

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2 via SCP
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no -r \
            ./app ./Dockerfile ./requirements.txt \
            ec2-user@${EC2_HOST}:~/HelloFastAPI

      - name: SSH into EC2 and redeploy container
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} << 'EOF'
          cd ~/HelloFastAPI
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker build -t hello-fastapi .
          docker run -d -p 80:8000 --name fastapi-app hello-fastapi
          EOF

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
